Search listings view
Agid-Kaharuba/SES_OSS pull request #16
Opened 2019-09-24 00:57 UTC by luminiferous

Created the specific listing page and listings page results from search query

2019-09-24 03:25 UTC, david-de-angelis reviewed
Pls undo all node_modules changes

2019-09-24 03:26 UTC, david-de-angelis requested changes
pls undo all node_modules changes

2019-09-24 11:27 UTC, Agid-Kaharuba commented
Could you also reorganize everything? Why is there a html2 directory, is it not suppose to be there or is it not organized?

2019-09-25 02:28 UTC, david-de-angelis approved these changes

2019-09-25 02:33 UTC, david-de-angelis approved these changes

2019-09-25 03:36 UTC, merged